### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Biepa** [n0b0dyCN/redis-rogue-server#4]
If someone else commes accross this.
I tried running the script with `python3 redis-rogue-server.py`. This resulted in 
```
[->] b'$1\r\n\x83\r\n'
[err ] UnicodeDecodeError('gb18030', b'$1\r\n\x83\r\n', 4, 5, 'illegal multibyte sequence')
```
Running `./redis-rogue-server.py` worked fine. The line before the error is then:
```
[->] b'$0\r\n\r\n'
```

**Comment by Biepa** [comment]
Tried it 3 times, it was always the same. Now on 4th try it works both ways. Strange. But ok.

**Comment by akatora28** [comment]
I can also confirm that I ran into this issue. Like @Biepa mentioned re-running the command a few more times without any other changes resolved it. If I have some spare time I might try to dig in and troubleshoot, but no ideas yet what the root cause is

**Comment by rayhernandez** [comment]
I also ran into this issue: `[err ] UnicodeDecodeError('gb18030', b'$1\r\n\x83\r\n', 4, 5, 'illegal multibyte sequence')`

I was able to get the script to work after changing Line 55 `return msg.decode('gb18030')` to `return msg.decode('utf-8', errors='replace')`.
